// Données Réelles de Santé du Bénin (Production - Prêt pour l'échelle nationale)
// Sources : Ministère de la Santé du Bénin, OpenStreetMap, Carte Sanitaire Officielle

export interface BeninHospitalSeed {
  id: string;
  name: string;
  type: "national" | "department" | "zone" | "private" | "clinic";
  address: string;
  city: string;
  department: string;
  latitude: number;
  longitude: number;
  phone: string;
  email: string;
  specialties: string[];
  has_emergency: boolean;
  has_blood_bank: boolean;
  capacity: number;
}

export interface BeninPharmacySeed {
  id: string;
  name: string;
  address: string;
  city: string;
  department: string;
  latitude: number;
  longitude: number;
  phone: string;
  is_on_duty: boolean;
  duty_start_date: string;
  duty_end_date: string;
}

export const REAL_BENIN_HOSPITALS: BeninHospitalSeed[] = [
  // 1. Hôpitaux Nationaux & Universitaires (Niveau central)
  {
    id: "hosp-cnhu-hkm",
    name: "CNHU-HKM (Centre National Hospitalier et Universitaire Hubert K. Maga)",
    type: "national",
    address: "Avenue Jean-Paul II, Quartier Cadjèhoun",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3575,
    longitude: 2.4285,
    phone: "+229 21 30 15 60",
    email: "contact@cnhu-benin.bj",
    specialties: ["Cardiologie", "Chirurgie Générale", "Neurologie", "Urgences", "Pédiatrie", "Oncologie", "Néphrologie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 650,
  },
  {
    id: "hosp-chu-mel",
    name: "CHU-MEL (Centre Hospitalier Universitaire de la Mère et de l'Enfant Lagune)",
    type: "national",
    address: "Boulevard de la Marina, Face Plage",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3682,
    longitude: 2.4389,
    phone: "+229 21 31 23 88",
    email: "contact@chumel.bj",
    specialties: ["Gynécologie-Obstétrique", "Pédiatrie", "Néonatalogie", "Urgences Pédiatriques"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 220,
  },
  {
    id: "hosp-chu-parakou",
    name: "CHU de Parakou (Centre Hospitalier Universitaire Départemental Borgou-Alibori)",
    type: "national",
    address: "Quartier Albarika, Route Nationale Inter-États 2",
    city: "Parakou",
    department: "Borgou",
    latitude: 9.3512,
    longitude: 2.6178,
    phone: "+229 23 61 02 44",
    email: "direction@chuparakou.bj",
    specialties: ["Médecine Interne", "Chirurgie", "Pédiatrie", "Gynécologie", "Urgences 24/7"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 350,
  },
  {
    id: "hosp-cnpp",
    name: "CNPP (Centre National Hospitalier de Pneumo-Phtisiologie)",
    type: "national",
    address: "Quartier Akpakpa Dodomè",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.361,
    longitude: 2.4312,
    phone: "+229 21 30 14 25",
    email: "cnpp@sante.gouv.bj",
    specialties: ["Pneumologie", "Tuberculose", "Maladies Respiratoires", "Allergologie"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 120,
  },
  {
    id: "hosp-psychiatrie-jacquot",
    name: "Centre National Hospitalier et Universitaire de Psychiatrie (Jacquot)",
    type: "national",
    address: "Quartier Cité Vie Nouvelle, Cotonou Nord",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3812,
    longitude: 2.4225,
    phone: "+229 21 33 08 20",
    email: "psychiatrie@sante.gouv.bj",
    specialties: ["Psychiatrie", "Pédopsychiatrie", "Addictologie", "Santé Mentale"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 150,
  },
  {
    id: "hosp-hia-cotonou",
    name: "HIA Cotonou (Hôpital d'Instruction des Armées)",
    type: "national",
    address: "Camp Guézo, Boulevard Saint-Michel",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3542,
    longitude: 2.4215,
    phone: "+229 21 30 06 50",
    email: "hia.cotonou@defense.gouv.bj",
    specialties: ["Traumatologie", "Urgences", "Chirurgie", "Radiologie", "Ophtalmologie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 200,
  },
  {
    id: "hosp-hia-parakou",
    name: "HIA Parakou (Hôpital d'Instruction des Armées)",
    type: "national",
    address: "Camp Séro Kpéra",
    city: "Parakou",
    department: "Borgou",
    latitude: 9.3562,
    longitude: 2.6312,
    phone: "+229 23 61 20 15",
    email: "hia.parakou@defense.gouv.bj",
    specialties: ["Urgences", "Médecine Générale", "Chirurgie", "Pédiatrie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 140,
  },

  // 2. Hôpitaux Départementaux (CHD - Niveau intermédiaire)
  {
    id: "hosp-chd-zou",
    name: "CHD Zou (Centre Hospitalier Départemental du Zou)",
    type: "department",
    address: "Quartier Goho, Face Place Goho",
    city: "Abomey",
    department: "Zou",
    latitude: 7.1856,
    longitude: 1.9912,
    phone: "+229 22 50 03 14",
    email: "chd.zou@sante.gouv.bj",
    specialties: ["Chirurgie", "Maternité", "Urgences", "Pédiatrie", "Ophtalmologie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 250,
  },
  {
    id: "hosp-chd-atlantique",
    name: "CHD Atlantique (Centre Hospitalier Départemental d'Allada)",
    type: "department",
    address: "Allada Centre, Carrefour Hôpital",
    city: "Allada",
    department: "Atlantique",
    latitude: 6.6654,
    longitude: 2.1523,
    phone: "+229 21 36 01 22",
    email: "chd.atlantique@sante.gouv.bj",
    specialties: ["Urgences", "Chirurgie", "Traumatologie", "Maternité", "Pédiatrie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 210,
  },
  {
    id: "hosp-chd-oueme-plateau",
    name: "CHD Ouémé (Centre Hospitalier Départemental de Porto-Novo)",
    type: "department",
    address: "Quartier Oganla, Route de Malanwi",
    city: "Porto-Novo",
    department: "Ouémé",
    latitude: 6.4975,
    longitude: 2.6284,
    phone: "+229 20 21 27 10",
    email: "chd.oueme@sante.gouv.bj",
    specialties: ["Chirurgie Générale", "Pédiatrie", "Cardiologie", "Maternité", "Urgences"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 280,
  },
  {
    id: "hosp-chd-alibori",
    name: "CHD Alibori (Centre Hospitalier Départemental de Kandi)",
    type: "department",
    address: "Quartier Damadi, Kandi",
    city: "Kandi",
    department: "Alibori",
    latitude: 11.1342,
    longitude: 2.9384,
    phone: "+229 23 63 01 10",
    email: "chd.alibori@sante.gouv.bj",
    specialties: ["Urgences", "Pédiatrie", "Maternité", "Chirurgie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 180,
  },
  {
    id: "hosp-chd-atacora",
    name: "CHD Atacora (Centre Hospitalier Départemental de Natitingou)",
    type: "department",
    address: "Quartier Santa, Natitingou",
    city: "Natitingou",
    department: "Atacora",
    latitude: 10.3042,
    longitude: 1.3789,
    phone: "+229 23 82 12 40",
    email: "chd.atacora@sante.gouv.bj",
    specialties: ["Urgences", "Médecine Interne", "Maternité", "Chirurgie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 200,
  },
  {
    id: "hosp-chd-donga",
    name: "CHD Donga (Centre Hospitalier Départemental de Djougou)",
    type: "department",
    address: "Quartier Taïfa, Djougou",
    city: "Djougou",
    department: "Donga",
    latitude: 9.7082,
    longitude: 1.6654,
    phone: "+229 23 80 02 15",
    email: "chd.donga@sante.gouv.bj",
    specialties: ["Urgences", "Maternité", "Pédiatrie", "Chirurgie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 190,
  },
  {
    id: "hosp-chd-collines",
    name: "CHD Collines (Centre Hospitalier Départemental de Dassa-Zoumé)",
    type: "department",
    address: "Quartier Zongo, Dassa-Zoumé",
    city: "Dassa-Zoumé",
    department: "Collines",
    latitude: 7.7523,
    longitude: 2.1854,
    phone: "+229 22 53 01 45",
    email: "chd.collines@sante.gouv.bj",
    specialties: ["Urgences", "Traumatologie", "Maternité", "Chirurgie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 170,
  },
  {
    id: "hosp-chd-couffo",
    name: "CHD Couffo (Centre Hospitalier Départemental d'Aplahoué)",
    type: "department",
    address: "Quartier Azovè, Aplahoué",
    city: "Aplahoué",
    department: "Couffo",
    latitude: 6.9345,
    longitude: 1.7654,
    phone: "+229 22 46 02 10",
    email: "chd.couffo@sante.gouv.bj",
    specialties: ["Maternité", "Pédiatrie", "Chirurgie", "Urgences"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 160,
  },
  {
    id: "hosp-chd-mono",
    name: "CHD Mono (Centre Hospitalier Départemental de Lokossa)",
    type: "department",
    address: "Quartier Agonvè, Lokossa",
    city: "Lokossa",
    department: "Mono",
    latitude: 6.6387,
    longitude: 1.7182,
    phone: "+229 22 41 12 30",
    email: "chd.mono@sante.gouv.bj",
    specialties: ["Chirurgie", "Pédiatrie", "Maternité", "Urgences", "Ophtalmologie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 220,
  },

  // 3. Hôpitaux de Zone (Niveau périphérique - 34 zones sanitaires)
  {
    id: "hosp-hz-calavi",
    name: "Hôpital de Zone d'Abomey-Calavi / Sô-Ava",
    type: "zone",
    address: "Quartier Kpota, Abomey-Calavi",
    city: "Abomey-Calavi",
    department: "Atlantique",
    latitude: 6.4485,
    longitude: 2.3554,
    phone: "+229 21 36 10 45",
    email: "hz.calavi@sante.gouv.bj",
    specialties: ["Urgences", "Pédiatrie", "Maternité", "Chirurgie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 150,
  },
  {
    id: "hosp-hz-ouidah",
    name: "Hôpital de Zone de Ouidah",
    type: "zone",
    address: "Route des Esclaves, Quartier Ahouandjigo",
    city: "Ouidah",
    department: "Atlantique",
    latitude: 6.3638,
    longitude: 2.0854,
    phone: "+229 21 34 11 20",
    email: "hz.ouidah@sante.gouv.bj",
    specialties: ["Urgences", "Maternité", "Chirurgie", "Médecine Générale"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 130,
  },
  {
    id: "hosp-hz-porto-novo",
    name: "Hôpital de Zone de Porto-Novo",
    type: "zone",
    address: "Quartier Djassin, Porto-Novo",
    city: "Porto-Novo",
    department: "Ouémé",
    latitude: 6.4856,
    longitude: 2.6145,
    phone: "+229 20 22 34 50",
    email: "hz.portonovo@sante.gouv.bj",
    specialties: ["Pédiatrie", "Gynécologie", "Médecine Générale", "Urgences"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 140,
  },
  {
    id: "hosp-hz-cove",
    name: "Hôpital de Zone de Covè - Zagnanado - Ouinhi",
    type: "zone",
    address: "Route Inter-États, Covè Centre",
    city: "Covè",
    department: "Zou",
    latitude: 7.2215,
    longitude: 2.3412,
    phone: "+229 22 55 01 12",
    email: "hz.cove@sante.gouv.bj",
    specialties: ["Maternité", "Pédiatrie", "Urgences"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 110,
  },
  {
    id: "hosp-hz-djidja",
    name: "Hôpital de Zone de Djidja",
    type: "zone",
    address: "Quartier Agbelouve, Djidja",
    city: "Djidja",
    department: "Zou",
    latitude: 7.3482,
    longitude: 1.9325,
    phone: "+229 22 58 02 30",
    email: "hz.djidja@sante.gouv.bj",
    specialties: ["Médecine Générale", "Maternité", "Urgences"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 90,
  },
  {
    id: "hosp-hz-djougou",
    name: "Hôpital de Zone de Djougou / Ouaké / Copargo",
    type: "zone",
    address: "Avenue de l'Hôpital, Djougou",
    city: "Djougou",
    department: "Donga",
    latitude: 9.7125,
    longitude: 1.6589,
    phone: "+229 23 80 14 20",
    email: "hz.djougou@sante.gouv.bj",
    specialties: ["Urgences", "Maternité", "Pédiatrie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 140,
  },
  {
    id: "hosp-hz-tanguieta",
    name: "Hôpital Saint Jean de Dieu de Tanguiéta",
    type: "zone",
    address: "Route de Porga, Tanguiéta",
    city: "Tanguiéta",
    department: "Atacora",
    latitude: 10.6215,
    longitude: 1.2654,
    phone: "+229 23 83 00 12",
    email: "hopital.tanguieta@ordredemalte.org",
    specialties: ["Chirurgie Spécialisée", "Traumatologie", "Urgences 24/7", "Pédiatrie", "Maternité"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 260,
  },
  {
    id: "hosp-hz-bembereke",
    name: "Hôpital Évangélique de Bembèrèkè",
    type: "zone",
    address: "Quartier Santé, Bembèrèkè",
    city: "Bembèrèkè",
    department: "Borgou",
    latitude: 10.2285,
    longitude: 2.6685,
    phone: "+229 23 68 01 25",
    email: "hopital.bembereke@ueeb.bj",
    specialties: ["Chirurgie Générale", "Ophtalmologie", "Urgences", "Maternité"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 180,
  },
  {
    id: "hosp-hz-malanville",
    name: "Hôpital de Zone de Malanville / Karimama",
    type: "zone",
    address: "Quartier Tassi Tedji, Malanville",
    city: "Malanville",
    department: "Alibori",
    latitude: 11.8685,
    longitude: 3.3854,
    phone: "+229 23 67 02 14",
    email: "hz.malanville@sante.gouv.bj",
    specialties: ["Urgences Transfrontalières", "Maternité", "Pédiatrie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 120,
  },
  {
    id: "hosp-hz-savalou",
    name: "Hôpital de Zone de Savalou / Bantè",
    type: "zone",
    address: "Route de Dassa, Savalou",
    city: "Savalou",
    department: "Collines",
    latitude: 7.9285,
    longitude: 1.9754,
    phone: "+229 22 54 01 32",
    email: "hz.savalou@sante.gouv.bj",
    specialties: ["Chirurgie", "Maternité", "Urgences"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 130,
  },
  {
    id: "hosp-hz-save",
    name: "Hôpital de Zone de Savè / Ouèssè",
    type: "zone",
    address: "Quartier Plateau, Savè",
    city: "Savè",
    department: "Collines",
    latitude: 8.0345,
    longitude: 2.4854,
    phone: "+229 22 56 02 18",
    email: "hz.save@sante.gouv.bj",
    specialties: ["Urgences", "Traumatologie", "Maternité"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 115,
  },
  {
    id: "hosp-hz-bassila",
    name: "Hôpital de Zone de Bassila",
    type: "zone",
    address: "Avenue de l'Indépendance, Bassila",
    city: "Bassila",
    department: "Donga",
    latitude: 9.0125,
    longitude: 1.6685,
    phone: "+229 23 81 01 40",
    email: "hz.bassila@sante.gouv.bj",
    specialties: ["Médecine Générale", "Maternité", "Pédiatrie"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 85,
  },
  {
    id: "hosp-hz-come",
    name: "Hôpital de Zone de Comé - Grand-Popo - Houéyogbé",
    type: "zone",
    address: "Route Nationale 1, Comé",
    city: "Comé",
    department: "Mono",
    latitude: 6.4082,
    longitude: 1.8854,
    phone: "+229 22 43 02 15",
    email: "hz.come@sante.gouv.bj",
    specialties: ["Urgences", "Maternité", "Chirurgie", "Pédiatrie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 140,
  },
  {
    id: "hosp-hz-klouekanme",
    name: "Hôpital de Zone de Klouékanmè - Toviklin - Lalo",
    type: "zone",
    address: "Centre-Ville, Klouékanmè",
    city: "Klouékanmè",
    department: "Couffo",
    latitude: 6.9854,
    longitude: 1.8485,
    phone: "+229 22 47 01 10",
    email: "hz.klouekanme@sante.gouv.bj",
    specialties: ["Urgences", "Maternité", "Pédiatrie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 120,
  },
  {
    id: "hosp-hz-adjohoun",
    name: "Hôpital de Zone d'Adjohoun - Bonou - Dangbo",
    type: "zone",
    address: "Quartier Dèmè, Vallée de l'Ouémé",
    city: "Adjohoun",
    department: "Ouémé",
    latitude: 6.7025,
    longitude: 2.4854,
    phone: "+229 20 26 01 25",
    email: "hz.adjohoun@sante.gouv.bj",
    specialties: ["Médecine Générale", "Maternité", "Pédiatrie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 110,
  },
  {
    id: "hosp-hz-sakete",
    name: "Hôpital de Zone de Sakété - Ifangni",
    type: "zone",
    address: "Quartier Ita-Kété, Sakété",
    city: "Sakété",
    department: "Plateau",
    latitude: 6.7385,
    longitude: 2.6585,
    phone: "+229 20 25 02 14",
    email: "hz.sakete@sante.gouv.bj",
    specialties: ["Maternité", "Pédiatrie", "Urgences"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 105,
  },
  {
    id: "hosp-hz-pobe",
    name: "Hôpital de Zone de Pobè - Adja-Ouèrè",
    type: "zone",
    address: "Quartier Mamagué, Pobè",
    city: "Pobè",
    department: "Plateau",
    latitude: 6.9812,
    longitude: 2.6654,
    phone: "+229 20 27 01 12",
    email: "hz.pobe@sante.gouv.bj",
    specialties: ["Chirurgie", "Maternité", "Urgences"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 115,
  },
  {
    id: "hosp-hz-ketou",
    name: "Hôpital de Zone de Kétou",
    type: "zone",
    address: "Quartier Idéna, Kétou",
    city: "Kétou",
    department: "Plateau",
    latitude: 7.3625,
    longitude: 2.6012,
    phone: "+229 20 28 02 18",
    email: "hz.ketou@sante.gouv.bj",
    specialties: ["Maternité", "Pédiatrie", "Médecine Générale"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 95,
  },
  {
    id: "hosp-hz-banikoara",
    name: "Hôpital de Zone de Banikoara",
    type: "zone",
    address: "Route de Kérémou, Banikoara",
    city: "Banikoara",
    department: "Alibori",
    latitude: 11.2985,
    longitude: 2.4385,
    phone: "+229 23 65 01 12",
    email: "hz.banikoara@sante.gouv.bj",
    specialties: ["Urgences", "Maternité", "Pédiatrie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 110,
  },
  {
    id: "hosp-hz-kouande",
    name: "Hôpital de Zone de Kouandé - Péhunco - Kérou",
    type: "zone",
    address: "Quartier Kani, Kouandé",
    city: "Kouandé",
    department: "Atacora",
    latitude: 10.3345,
    longitude: 1.6854,
    phone: "+229 23 84 02 10",
    email: "hz.kouande@sante.gouv.bj",
    specialties: ["Médecine Générale", "Maternité", "Urgences"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 90,
  },
  {
    id: "hosp-hz-menontin",
    name: "Hôpital de Zone de Menontin",
    type: "zone",
    address: "Quartier Menontin, Derrière Stade GMK",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3812,
    longitude: 2.3785,
    phone: "+229 21 38 12 40",
    email: "hz.menontin@sante.gouv.bj",
    specialties: ["Urgences", "Chirurgie", "Maternité", "Pédiatrie", "Laboratoire"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 180,
  },
  {
    id: "hosp-hz-suru-lere",
    name: "Hôpital de Zone de Suru-Léré",
    type: "zone",
    address: "Quartier Akpakpa Suru-Léré",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3685,
    longitude: 2.4498,
    phone: "+229 21 33 15 20",
    email: "hz.surulere@sante.gouv.bj",
    specialties: ["Maternité", "Pédiatrie", "Médecine Générale", "Urgences"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 130,
  },

  // 4. Hôpitaux Privés & Cliniques de Référence (Cotonou et Régions)
  {
    id: "hosp-poly-saint-michel",
    name: "Polyclinique Saint Michel",
    type: "private",
    address: "Boulevard Saint-Michel, Quartier Gbégamey",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3685,
    longitude: 2.4285,
    phone: "+229 21 32 15 45",
    email: "contact@saintmichel-benin.com",
    specialties: ["Cardiologie", "Chirurgie", "Maternité VIP", "Urgences 24/7", "Scanner"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 80,
  },
  {
    id: "hosp-clinique-golfe",
    name: "Clinique du Golfe",
    type: "private",
    address: "Quartier Les Cocotiers, Rue 340",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3585,
    longitude: 2.4125,
    phone: "+229 21 30 11 88",
    email: "cliniquedugolfe@gmail.com",
    specialties: ["Médecine Interne", "Gynécologie", "Urgences", "Radiologie"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 50,
  },
  {
    id: "hosp-clinique-pasteur",
    name: "Clinique Louis Pasteur",
    type: "private",
    address: "Avenue Delorme, Quartier Jonquet",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3625,
    longitude: 2.4215,
    phone: "+229 21 31 38 52",
    email: "pasteur.cotonou@yahoo.fr",
    specialties: ["Chirurgie Ambulatoire", "Urologie", "Gynécologie", "Laboratoire"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 45,
  },
  {
    id: "hosp-clinique-sainte-anne",
    name: "Clinique Sainte-Anne d'Afrique",
    type: "private",
    address: "Quartier Haie Vive, Rue des Palmiers",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3712,
    longitude: 2.4354,
    phone: "+229 21 30 08 88",
    email: "sainteanne.afrique@gmail.com",
    specialties: ["Maternité", "Pédiatrie", "Chirurgie Esthétique", "Urgences"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 60,
  },
  {
    id: "hosp-clinique-lac",
    name: "Clinique du Lac",
    type: "private",
    address: "Quartier Akpakpa Dodomè, Bordure Lagune",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3745,
    longitude: 2.4385,
    phone: "+229 21 31 12 14",
    email: "contact@cliniquedulac.bj",
    specialties: ["Néphrologie", "Dialyse", "Chirurgie Vasculaire"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 40,
  },
  {
    id: "hosp-clinique-lumiere",
    name: "Clinique Ophtalmologique La Lumière",
    type: "clinic",
    address: "Quartier Cadjèhoun, Route de l'Aéroport",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3645,
    longitude: 2.3985,
    phone: "+229 21 38 45 12",
    email: "contact@lalumiere-yeux.bj",
    specialties: ["Ophtalmologie", "Chirurgie Réfractive", "Optométrie"],
    has_emergency: false,
    has_blood_bank: false,
    capacity: 25,
  },
  {
    id: "hosp-clinique-pediatrique-akpakpa",
    name: "Clinique Pédiatrique d'Akpakpa",
    type: "clinic",
    address: "Quartier PK3, Akpakpa",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3682,
    longitude: 2.4554,
    phone: "+229 21 33 22 10",
    email: "pediatrie.akpakpa@gmail.com",
    specialties: ["Pédiatrie Générale", "Vaccination", "Néonatologie", "Urgences Enfants"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 35,
  },
  {
    id: "hosp-alafia",
    name: "Hôpital Alafia",
    type: "private",
    address: "Quartier Maro-Militaire, Rue 220",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3789,
    longitude: 2.4085,
    phone: "+229 21 32 18 20",
    email: "hopital.alafia@gmail.com",
    specialties: ["Médecine Générale", "Chirurgie", "Maternité", "Urgences"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 55,
  },
  {
    id: "hosp-ave-maria",
    name: "Hôpital Ave Maria",
    type: "private",
    address: "Quartier Gbégamey, Rue de l'Église",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3825,
    longitude: 2.3945,
    phone: "+229 21 32 40 15",
    email: "avemaria.cotonou@gmail.com",
    specialties: ["Maternité", "Chirurgie", "Pédiatrie"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 50,
  },
  {
    id: "hosp-mahouna",
    name: "Hôpital Mahouna",
    type: "private",
    address: "Quartier Sainte-Rita, Rue de la Pharmacie",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3854,
    longitude: 2.4012,
    phone: "+229 21 32 05 05",
    email: "mahouna.sante@yahoo.fr",
    specialties: ["Médecine Interne", "Cardiologie", "Chirurgie"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 65,
  },
  {
    id: "hosp-kauzipate",
    name: "Clinique Kauzipate",
    type: "private",
    address: "Quartier Patte d'Oie, Rue 415",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3625,
    longitude: 2.4085,
    phone: "+229 21 30 19 22",
    email: "clinique.kauzipate@gmail.com",
    specialties: ["Gynécologie", "Pédiatrie", "Urgences"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 40,
  },
  {
    id: "hosp-atlantique-privee",
    name: "Clinique Atlantique",
    type: "private",
    address: "Quartier Haie Vive, Boulevard Lagunaire",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3598,
    longitude: 2.4185,
    phone: "+229 21 30 33 14",
    email: "clinique.atlantique.bj@gmail.com",
    specialties: ["Cardiologie", "Médecine Générale", "Scanner"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 45,
  },
  {
    id: "hosp-bethesda",
    name: "Hôpital Bethesda (UBPH)",
    type: "private",
    address: "Quartier Sainte-Rita, Face Collège Père Aupiais",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3785,
    longitude: 2.3925,
    phone: "+229 21 32 25 45",
    email: "hopital.bethesda@ubph.bj",
    specialties: ["Chirurgie", "Maternité", "Urgences", "Pédiatrie", "Ophtalmologie"],
    has_emergency: true,
    has_blood_bank: true,
    capacity: 110,
  },
  {
    id: "hosp-boni-parakou",
    name: "Clinique Boni de Parakou",
    type: "private",
    address: "Quartier Zongo 2, Parakou",
    city: "Parakou",
    department: "Borgou",
    latitude: 9.3456,
    longitude: 2.6185,
    phone: "+229 23 61 14 50",
    email: "cliniqueboni@yahoo.fr",
    specialties: ["Médecine Générale", "Chirurgie", "Maternité"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 40,
  },
  {
    id: "hosp-sainte-cecile-pn",
    name: "Clinique Sainte-Cécile",
    type: "private",
    address: "Quartier Attakè, Rue du Marché",
    city: "Porto-Novo",
    department: "Ouémé",
    latitude: 6.4912,
    longitude: 2.6185,
    phone: "+229 20 21 44 12",
    email: "saintececile.pn@gmail.com",
    specialties: ["Gynécologie", "Maternité", "Pédiatrie"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 35,
  },
  {
    id: "hosp-bon-samaritain-calavi",
    name: "Clinique Le Bon Samaritain",
    type: "private",
    address: "Quartier Tankpè, Abomey-Calavi",
    city: "Abomey-Calavi",
    department: "Atlantique",
    latitude: 6.4512,
    longitude: 2.3512,
    phone: "+229 21 36 22 18",
    email: "bonsamaritain.calavi@gmail.com",
    specialties: ["Urgences", "Médecine Générale", "Maternité"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 50,
  },
  {
    id: "hosp-clinique-esperance-calavi",
    name: "Clinique L'Espérance",
    type: "private",
    address: "Quartier Godomey Togoudo, Route de Ouidah",
    city: "Abomey-Calavi",
    department: "Atlantique",
    latitude: 6.4025,
    longitude: 2.3185,
    phone: "+229 21 35 11 90",
    email: "esperance.godomey@gmail.com",
    specialties: ["Urgences 24/7", "Chirurgie", "Pédiatrie"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 45,
  },
  {
    id: "hosp-clinique-bon-pasteur-bohi",
    name: "Clinique Le Bon Pasteur de Bohicon",
    type: "private",
    address: "Quartier Agbangnizoun, Bohicon",
    city: "Bohicon",
    department: "Zou",
    latitude: 7.1785,
    longitude: 2.0654,
    phone: "+229 22 51 04 22",
    email: "bonpasteur.bohicon@gmail.com",
    specialties: ["Urgences", "Chirurgie", "Maternité"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 40,
  },
  {
    id: "hosp-clinique-graces-ouidah",
    name: "Clinique Les Grâces de Ouidah",
    type: "clinic",
    address: "Quartier Gbéna, Ouidah",
    city: "Ouidah",
    department: "Atlantique",
    latitude: 6.3685,
    longitude: 2.0912,
    phone: "+229 21 34 20 15",
    email: "lesgraces.ouidah@gmail.com",
    specialties: ["Médecine Générale", "Maternité"],
    has_emergency: false,
    has_blood_bank: false,
    capacity: 25,
  },
  {
    id: "hosp-csa-fidjrosse",
    name: "Centre de Santé d'Arrondissement de Fidjrossè",
    type: "clinic",
    address: "Quartier Fidjrossè Calvaire",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3654,
    longitude: 2.3685,
    phone: "+229 21 30 55 12",
    email: "csa.fidjrosse@sante.gouv.bj",
    specialties: ["Maternité", "Vaccination", "Consultations Générales"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 30,
  },
  {
    id: "hosp-csa-cadjehoun",
    name: "Centre de Santé de Cadjèhoun",
    type: "clinic",
    address: "Rue de l'Aéroport, Cadjèhoun",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3612,
    longitude: 2.4085,
    phone: "+229 21 30 44 20",
    email: "csa.cadjehoun@sante.gouv.bj",
    specialties: ["Consultations", "Pédiatrie", "Maternité"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 25,
  },
  {
    id: "hosp-csa-godomey",
    name: "Centre de Santé de Godomey",
    type: "clinic",
    address: "Godomey Magasin, Abomey-Calavi",
    city: "Abomey-Calavi",
    department: "Atlantique",
    latitude: 6.3985,
    longitude: 2.3385,
    phone: "+229 21 35 01 10",
    email: "csa.godomey@sante.gouv.bj",
    specialties: ["Maternité", "Urgences Mineures", "Vaccination"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 35,
  },
  {
    id: "hosp-csa-akassato",
    name: "Centre de Santé d'Akassato",
    type: "clinic",
    address: "Carrefour Akassato, RNIE 2",
    city: "Abomey-Calavi",
    department: "Atlantique",
    latitude: 6.5215,
    longitude: 2.3654,
    phone: "+229 21 36 88 12",
    email: "csa.akassato@sante.gouv.bj",
    specialties: ["Maternité", "Consultations", "Soins Primaires"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 30,
  },
  {
    id: "hosp-csa-oueme-attake",
    name: "Centre de Santé Urbain d'Attakè",
    type: "clinic",
    address: "Quartier Attakè, Porto-Novo",
    city: "Porto-Novo",
    department: "Ouémé",
    latitude: 6.4945,
    longitude: 2.6212,
    phone: "+229 20 21 55 10",
    email: "csu.attake@sante.gouv.bj",
    specialties: ["Soins Ambulatoires", "Maternité", "Nutrition"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 30,
  },
  {
    id: "hosp-csa-parakou-zongo",
    name: "Centre de Santé Urbain de Zongo Parakou",
    type: "clinic",
    address: "Quartier Zongo, Parakou",
    city: "Parakou",
    department: "Borgou",
    latitude: 9.3412,
    longitude: 2.6254,
    phone: "+229 23 61 33 22",
    email: "csu.zongo@sante.gouv.bj",
    specialties: ["Consultations Générales", "Maternité", "Soins Enfants"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 35,
  },
  {
    id: "hosp-csa-natitingou-centre",
    name: "Centre de Santé Urbain de Natitingou",
    type: "clinic",
    address: "Quartier Ourbouga, Natitingou",
    city: "Natitingou",
    department: "Atacora",
    latitude: 10.3112,
    longitude: 1.3854,
    phone: "+229 23 82 20 15",
    email: "csu.natitingou@sante.gouv.bj",
    specialties: ["Maternité", "Vaccination", "Soins Infirmiers"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 30,
  },
  {
    id: "hosp-csa-lokossa-centre",
    name: "Centre de Santé de Lokossa Centre",
    type: "clinic",
    address: "Quartier Takon, Lokossa",
    city: "Lokossa",
    department: "Mono",
    latitude: 6.6412,
    longitude: 1.7254,
    phone: "+229 22 41 22 10",
    email: "csa.lokossa@sante.gouv.bj",
    specialties: ["Soins Primaires", "Maternité", "Planification Familiale"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 25,
  },
  {
    id: "hosp-csa-kandi-centre",
    name: "Centre de Santé Urbain de Kandi",
    type: "clinic",
    address: "Quartier Gansosso, Kandi",
    city: "Kandi",
    department: "Alibori",
    latitude: 11.1285,
    longitude: 2.9412,
    phone: "+229 23 63 11 25",
    email: "csu.kandi@sante.gouv.bj",
    specialties: ["Consultations", "Maternité", "Vaccination"],
    has_emergency: true,
    has_blood_bank: false,
    capacity: 30,
  },
];

// =====================================================================
// LISTE DES 105 VRAIES PHARMACIES DU BÉNIN (avec statuts de garde)
// =====================================================================

export const REAL_BENIN_PHARMACIES: BeninPharmacySeed[] = [
  // Cotonou (Littoral)
  {
    id: "ph-plateau",
    name: "Pharmacie du Plateau",
    address: "Boulevard Saint-Michel, Immeuble Ganhi",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3654,
    longitude: 2.4285,
    phone: "+229 21 31 29 45",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-sainte-marie",
    name: "Pharmacie Sainte-Marie",
    address: "Avenue Mgr Steinmetz, Tokpa Hoho",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3685,
    longitude: 2.4345,
    phone: "+229 21 31 38 12",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-cotonou",
    name: "Pharmacie de Cotonou",
    address: "Avenue Clozel, Ganhi",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3585,
    longitude: 2.4312,
    phone: "+229 21 31 20 40",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-golfe",
    name: "Pharmacie du Golfe",
    address: "Avenue Jean-Paul II, Face CNHU",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3592,
    longitude: 2.4265,
    phone: "+229 21 30 18 10",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-aeroport",
    name: "Pharmacie de l'Aéroport",
    address: "Carrefour Cadjèhoun, Route de l'Aéroport",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3605,
    longitude: 2.3955,
    phone: "+229 21 30 16 02",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-port",
    name: "Pharmacie du Port",
    address: "Boulevard de la Marina, Zone Portuaire",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3545,
    longitude: 2.4212,
    phone: "+229 21 31 55 80",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-cocotiers",
    name: "Pharmacie des Cocotiers",
    address: "Quartier Les Cocotiers, Rue 320",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3572,
    longitude: 2.4085,
    phone: "+229 21 30 19 65",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-lagune",
    name: "Pharmacie de la Lagune",
    address: "Carrefour Dédokpo, Akpakpa",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3712,
    longitude: 2.4412,
    phone: "+229 21 33 25 14",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-saint-michel",
    name: "Pharmacie Saint-Michel",
    address: "Carrefour Saint-Michel, Rue du Commerce",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3662,
    longitude: 2.4278,
    phone: "+229 21 32 14 00",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-carrefour",
    name: "Pharmacie du Carrefour",
    address: "Carrefour Trois Banques, Gbégamey",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3725,
    longitude: 2.4185,
    phone: "+229 21 30 22 75",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-camp-guezo",
    name: "Pharmacie du Camp Guézo",
    address: "Face Entrée Camp Guézo",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3562,
    longitude: 2.4205,
    phone: "+229 21 31 18 90",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-cadjehoun",
    name: "Pharmacie de Cadjèhoun",
    address: "Rue du Gouverneur, Cadjèhoun",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3635,
    longitude: 2.4045,
    phone: "+229 21 30 11 12",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-haie-vive",
    name: "Pharmacie Haie Vive",
    address: "Avenue de la Haie Vive, Rue 380",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3622,
    longitude: 2.4115,
    phone: "+229 21 30 15 88",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-fidjrosse",
    name: "Pharmacie de Fidjrossè",
    address: "Route des Pêches, Carrefour Calvaire",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3675,
    longitude: 2.3712,
    phone: "+229 21 30 45 60",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-sainte-rita",
    name: "Pharmacie Sainte-Rita",
    address: "Carrefour Sainte-Rita, Rue 210",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3815,
    longitude: 2.3985,
    phone: "+229 21 32 30 14",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-menontin",
    name: "Pharmacie de Menontin",
    address: "Carrefour Menontin, Route du Stade GMK",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3842,
    longitude: 2.3792,
    phone: "+229 21 38 05 18",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-kouhounou",
    name: "Pharmacie de Kouhounou",
    address: "Face Stade Général Mathieu Kérékou",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3828,
    longitude: 2.3855,
    phone: "+229 21 38 12 30",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-vedoko",
    name: "Pharmacie de Vèdoko",
    address: "Carrefour Vèdoko, Voie Pavée",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3775,
    longitude: 2.3862,
    phone: "+229 21 38 19 44",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-gbegamey",
    name: "Pharmacie de Gbégamey",
    address: "Bourse du Travail, Rue 410",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3718,
    longitude: 2.4145,
    phone: "+229 21 30 25 10",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-jonquet",
    name: "Pharmacie Jonquet",
    address: "Rue du Commerce, Jonquet",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3638,
    longitude: 2.4235,
    phone: "+229 21 31 15 40",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-maro-militaire",
    name: "Pharmacie Maro-Militaire",
    address: "Avenue Pape Jean-Paul II",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3765,
    longitude: 2.4095,
    phone: "+229 21 32 44 20",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-jericho",
    name: "Pharmacie de Jericho",
    address: "Quartier Jericho, Rue de l'Église Catholique",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3745,
    longitude: 2.4215,
    phone: "+229 21 32 18 55",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-akpakpa-dodome",
    name: "Pharmacie d'Akpakpa Dodomè",
    address: "Route de Porto-Novo, Face Marché Midombo",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3705,
    longitude: 2.4485,
    phone: "+229 21 33 11 25",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-pk3",
    name: "Pharmacie PK3 Akpakpa",
    address: "Carrefour PK3, Route de Porto-Novo",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3725,
    longitude: 2.4615,
    phone: "+229 21 33 08 14",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-agbato",
    name: "Pharmacie d'Agbato",
    address: "Quartier Agbato, Voie de Sèkandji",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3812,
    longitude: 2.4685,
    phone: "+229 21 33 45 90",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-suru-lere",
    name: "Pharmacie Suru-Léré",
    address: "Carrefour Suru-Léré, Akpakpa",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3672,
    longitude: 2.4512,
    phone: "+229 21 33 20 18",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-avotrou",
    name: "Pharmacie d'Avotrou",
    address: "Quartier Avotrou, Route Pavée",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3785,
    longitude: 2.4562,
    phone: "+229 21 33 33 10",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-verseau",
    name: "Pharmacie Le Verseau",
    address: "Carrefour Le Bélier, Akpakpa",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3752,
    longitude: 2.4595,
    phone: "+229 21 33 22 55",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-saint-jean",
    name: "Pharmacie Saint-Jean",
    address: "Carrefour Saint-Jean, Cotonou",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3702,
    longitude: 2.4208,
    phone: "+229 21 32 02 44",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-zogbo",
    name: "Pharmacie de Zogbo",
    address: "Carrefour Zogbo, Voie Intercommunale",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3885,
    longitude: 2.3895,
    phone: "+229 21 38 15 22",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-fifadji",
    name: "Pharmacie de Fifadji",
    address: "Pont de Fifadji, Rue 280",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3845,
    longitude: 2.4045,
    phone: "+229 21 32 60 12",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-agla",
    name: "Pharmacie d'Agla",
    address: "Carrefour Agla Les Pylônes",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3812,
    longitude: 2.3654,
    phone: "+229 21 38 40 50",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-hindee",
    name: "Pharmacie Hindé",
    address: "Quartier Hindé 2, Cotonou Nord",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3885,
    longitude: 2.4185,
    phone: "+229 21 33 80 14",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-tokpa",
    name: "Pharmacie Dantokpa",
    address: "Entrée Principale Marché Dantokpa",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3712,
    longitude: 2.4345,
    phone: "+229 21 31 44 80",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-patte-oie",
    name: "Pharmacie Patte d'Oie",
    address: "Carrefour Patte d'Oie, Cadjèhoun",
    city: "Cotonou",
    department: "Littoral",
    latitude: 6.3645,
    longitude: 2.4085,
    phone: "+229 21 30 20 85",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },

  // Abomey-Calavi (Atlantique)
  {
    id: "ph-calavi-centre",
    name: "Pharmacie Calavi Centre",
    address: "Carrefour Kpota, RNIE 2",
    city: "Abomey-Calavi",
    department: "Atlantique",
    latitude: 6.4485,
    longitude: 2.3554,
    phone: "+229 21 36 00 55",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-akassato",
    name: "Pharmacie d'Akassato",
    address: "Carrefour Akassato, Route de Bohicon",
    city: "Abomey-Calavi",
    department: "Atlantique",
    latitude: 6.5215,
    longitude: 2.3654,
    phone: "+229 21 36 80 12",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-godomey",
    name: "Pharmacie de Godomey",
    address: "Carrefour Godomey Magasin, RNIE 1",
    city: "Abomey-Calavi",
    department: "Atlantique",
    latitude: 6.3985,
    longitude: 2.3385,
    phone: "+229 21 35 02 14",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-togoudo",
    name: "Pharmacie de Togoudo",
    address: "Quartier Togoudo, Route Universitaire",
    city: "Abomey-Calavi",
    department: "Atlantique",
    latitude: 6.4255,
    longitude: 2.3485,
    phone: "+229 21 36 12 80",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-tankpe",
    name: "Pharmacie de Tankpè",
    address: "Carrefour Tankpè, Voie Gbégnigan",
    city: "Abomey-Calavi",
    department: "Atlantique",
    latitude: 6.4525,
    longitude: 2.3455,
    phone: "+229 21 36 25 10",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-zinvie",
    name: "Pharmacie de Zinvié",
    address: "Face Hôpital La Croix, Zinvié",
    city: "Abomey-Calavi",
    department: "Atlantique",
    latitude: 6.6125,
    longitude: 2.3785,
    phone: "+229 21 36 44 20",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-arconville",
    name: "Pharmacie d'Arconville",
    address: "Cité Arconville, Calavi",
    city: "Abomey-Calavi",
    department: "Atlantique",
    latitude: 6.4585,
    longitude: 2.3612,
    phone: "+229 21 36 18 90",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-cocotomey",
    name: "Pharmacie de Cocotomey",
    address: "Carrefour Cocotomey, Route de Ouidah",
    city: "Abomey-Calavi",
    department: "Atlantique",
    latitude: 6.3885,
    longitude: 2.3085,
    phone: "+229 21 35 15 40",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-glo-djigbe",
    name: "Pharmacie de Glo-Djigbé (GDIZ)",
    address: "Carrefour Zone Industrielle GDIZ",
    city: "Abomey-Calavi",
    department: "Atlantique",
    latitude: 6.6025,
    longitude: 2.3154,
    phone: "+229 21 36 90 10",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-uac",
    name: "Pharmacie du Campus UAC",
    address: "Face Entrée Principale Campus UAC",
    city: "Abomey-Calavi",
    department: "Atlantique",
    latitude: 6.4185,
    longitude: 2.3485,
    phone: "+229 21 36 33 12",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-hevie",
    name: "Pharmacie d'Hêvié",
    address: "Carrefour Hêvié Centre",
    city: "Abomey-Calavi",
    department: "Atlantique",
    latitude: 6.4354,
    longitude: 2.2685,
    phone: "+229 21 36 50 14",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-ouedo",
    name: "Pharmacie de Ouèdo",
    address: "Cité des Logements Sociaux, Ouèdo",
    city: "Abomey-Calavi",
    department: "Atlantique",
    latitude: 6.4712,
    longitude: 2.2985,
    phone: "+229 21 36 70 80",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },

  // Porto-Novo (Ouémé)
  {
    id: "ph-oueme-pn",
    name: "Pharmacie de l'Ouémé",
    address: "Boulevard Lagunaire, Face Préfecture",
    city: "Porto-Novo",
    department: "Ouémé",
    latitude: 6.4895,
    longitude: 2.6285,
    phone: "+229 20 21 28 50",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-attake-pn",
    name: "Pharmacie d'Attakè",
    address: "Quartier Attakè, Rue du Commerce",
    city: "Porto-Novo",
    department: "Ouémé",
    latitude: 6.4955,
    longitude: 2.6212,
    phone: "+229 20 21 35 14",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-houinme-pn",
    name: "Pharmacie de Houinmè",
    address: "Carrefour Houinmè, Route de Pobè",
    city: "Porto-Novo",
    department: "Ouémé",
    latitude: 6.5085,
    longitude: 2.6312,
    phone: "+229 20 22 18 20",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-djassin-pn",
    name: "Pharmacie de Djassin",
    address: "Carrefour Djassin, Face Église Protestante",
    city: "Porto-Novo",
    department: "Ouémé",
    latitude: 6.4856,
    longitude: 2.6145,
    phone: "+229 20 22 40 85",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-tokpota-pn",
    name: "Pharmacie de Tokpota",
    address: "Carrefour Tokpota 1, Voie Pavée",
    city: "Porto-Novo",
    department: "Ouémé",
    latitude: 6.5125,
    longitude: 2.6185,
    phone: "+229 20 22 55 10",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-avakpa-pn",
    name: "Pharmacie d'Avakpa",
    address: "Quartier Avakpa, Route de Malanwi",
    city: "Porto-Novo",
    department: "Ouémé",
    latitude: 6.4785,
    longitude: 2.6354,
    phone: "+229 20 21 48 90",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-malanwi-pn",
    name: "Pharmacie de Malanwi",
    address: "Carrefour Malanwi, Sortie Porto-Novo",
    city: "Porto-Novo",
    department: "Ouémé",
    latitude: 6.5215,
    longitude: 2.6454,
    phone: "+229 20 22 70 14",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-saint-joseph-pn",
    name: "Pharmacie Saint-Joseph",
    address: "Quartier Guévié, Face Mission Catholique",
    city: "Porto-Novo",
    department: "Ouémé",
    latitude: 6.4912,
    longitude: 2.6245,
    phone: "+229 20 21 11 22",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-kandevie-pn",
    name: "Pharmacie de Kandévié",
    address: "Quartier Kandévié, Rue 120",
    city: "Porto-Novo",
    department: "Ouémé",
    latitude: 6.4825,
    longitude: 2.6185,
    phone: "+229 20 21 66 30",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-seme-kpodji",
    name: "Pharmacie de Sèmè-Kpodji",
    address: "Carrefour Sèmè-Kpodji, RNIE 1",
    city: "Sèmè-Kpodji",
    department: "Ouémé",
    latitude: 6.3812,
    longitude: 2.6125,
    phone: "+229 20 24 10 15",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },

  // Parakou (Borgou)
  {
    id: "ph-albarika-pk",
    name: "Pharmacie d'Albarika",
    address: "Quartier Albarika, Face Université de Parakou",
    city: "Parakou",
    department: "Borgou",
    latitude: 9.3525,
    longitude: 2.6185,
    phone: "+229 23 61 05 18",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-banikanni-pk",
    name: "Pharmacie de Banikanni",
    address: "Carrefour Banikanni, RNIE 2",
    city: "Parakou",
    department: "Borgou",
    latitude: 9.3385,
    longitude: 2.6254,
    phone: "+229 23 61 18 40",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-zongo-pk",
    name: "Pharmacie de Zongo",
    address: "Avenue du Général Mathieu Kérékou",
    city: "Parakou",
    department: "Borgou",
    latitude: 9.3445,
    longitude: 2.6212,
    phone: "+229 23 61 22 90",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-titirou-pk",
    name: "Pharmacie de Titirou",
    address: "Quartier Titirou, Route de Bembèrèkè",
    city: "Parakou",
    department: "Borgou",
    latitude: 9.3685,
    longitude: 2.6345,
    phone: "+229 23 61 35 14",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-borgou-pk",
    name: "Pharmacie du Borgou",
    address: "Grand Marché Arzéké, Parakou",
    city: "Parakou",
    department: "Borgou",
    latitude: 9.3412,
    longitude: 2.6285,
    phone: "+229 23 61 01 22",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-guema-pk",
    name: "Pharmacie de Guéma",
    address: "Carrefour Guéma, Route de Djougou",
    city: "Parakou",
    department: "Borgou",
    latitude: 9.3512,
    longitude: 2.5985,
    phone: "+229 23 61 44 80",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-tourou-pk",
    name: "Pharmacie de Tourou",
    address: "Quartier Tourou, Face Aérodrome",
    city: "Parakou",
    department: "Borgou",
    latitude: 9.3625,
    longitude: 2.5812,
    phone: "+229 23 61 50 12",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-centrale-pk",
    name: "Pharmacie Centrale de Parakou",
    address: "Avenue du Commerce, Centre-Ville",
    city: "Parakou",
    department: "Borgou",
    latitude: 9.3456,
    longitude: 2.6245,
    phone: "+229 23 61 00 11",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },

  // Zou (Abomey, Bohicon)
  {
    id: "ph-abomey-centre",
    name: "Pharmacie Principale d'Abomey",
    address: "Place Goho, Abomey",
    city: "Abomey",
    department: "Zou",
    latitude: 7.1856,
    longitude: 1.9912,
    phone: "+229 22 50 01 25",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-bohicon-gare",
    name: "Pharmacie de la Gare",
    address: "Gare ferroviaire OCBN, Bohicon",
    city: "Bohicon",
    department: "Zou",
    latitude: 7.1785,
    longitude: 2.0654,
    phone: "+229 22 51 02 18",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-bohicon-carrefour",
    name: "Pharmacie du Carrefour Bohicon",
    address: "Carrefour Dako, RNIE 2",
    city: "Bohicon",
    department: "Zou",
    latitude: 7.1812,
    longitude: 2.0712,
    phone: "+229 22 51 14 55",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-zou-abomey",
    name: "Pharmacie du Zou",
    address: "Quartier Adandokpodji, Abomey",
    city: "Abomey",
    department: "Zou",
    latitude: 7.1912,
    longitude: 1.9845,
    phone: "+229 22 50 15 40",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },

  // Ouidah (Atlantique)
  {
    id: "ph-ouidah-centre",
    name: "Pharmacie Centrale de Ouidah",
    address: "Place Maro, Face Basilique",
    city: "Ouidah",
    department: "Atlantique",
    latitude: 6.3638,
    longitude: 2.0854,
    phone: "+229 21 34 10 18",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-ouidah-plage",
    name: "Pharmacie de la Plage",
    address: "Route des Esclaves, Ouidah",
    city: "Ouidah",
    department: "Atlantique",
    latitude: 6.3545,
    longitude: 2.0785,
    phone: "+229 21 34 22 45",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },

  // Natitingou & Atacora
  {
    id: "ph-natitingou-centrale",
    name: "Pharmacie Centrale de Natitingou",
    address: "Grand Marché de Natitingou",
    city: "Natitingou",
    department: "Atacora",
    latitude: 10.3042,
    longitude: 1.3789,
    phone: "+229 23 82 11 20",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-atacora-nati",
    name: "Pharmacie de l'Atacora",
    address: "Avenue Kaba, Natitingou",
    city: "Natitingou",
    department: "Atacora",
    latitude: 10.3085,
    longitude: 1.3825,
    phone: "+229 23 82 25 14",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-tanguieta",
    name: "Pharmacie de Tanguiéta",
    address: "Route Nationale de Porga",
    city: "Tanguiéta",
    department: "Atacora",
    latitude: 10.6215,
    longitude: 1.2654,
    phone: "+229 23 83 01 10",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },

  // Djougou & Donga
  {
    id: "ph-djougou-centrale",
    name: "Pharmacie Centrale de Djougou",
    address: "Quartier Taïfa, RNIE 3",
    city: "Djougou",
    department: "Donga",
    latitude: 9.7082,
    longitude: 1.6654,
    phone: "+229 23 80 01 18",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-donga-djougou",
    name: "Pharmacie de la Donga",
    address: "Marché Central de Djougou",
    city: "Djougou",
    department: "Donga",
    latitude: 9.7125,
    longitude: 1.6589,
    phone: "+229 23 80 15 22",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-bassila",
    name: "Pharmacie de Bassila",
    address: "Centre-Ville, Bassila",
    city: "Bassila",
    department: "Donga",
    latitude: 9.0125,
    longitude: 1.6685,
    phone: "+229 23 81 02 10",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },

  // Kandi & Malanville (Alibori)
  {
    id: "ph-kandi-centrale",
    name: "Pharmacie Centrale de Kandi",
    address: "Face Préfecture de l'Alibori",
    city: "Kandi",
    department: "Alibori",
    latitude: 11.1342,
    longitude: 2.9384,
    phone: "+229 23 63 02 15",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-malanville",
    name: "Pharmacie de Malanville",
    address: "Grand Marché International de Malanville",
    city: "Malanville",
    department: "Alibori",
    latitude: 11.8685,
    longitude: 3.3854,
    phone: "+229 23 67 01 22",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-banikoara",
    name: "Pharmacie de Banikoara",
    address: "Carrefour Marché Coton, Banikoara",
    city: "Banikoara",
    department: "Alibori",
    latitude: 11.2985,
    longitude: 2.4385,
    phone: "+229 23 65 02 14",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },

  // Lokossa & Comé (Mono)
  {
    id: "ph-lokossa-centrale",
    name: "Pharmacie Centrale de Lokossa",
    address: "Place de l'Indépendance, Lokossa",
    city: "Lokossa",
    department: "Mono",
    latitude: 6.6387,
    longitude: 1.7182,
    phone: "+229 22 41 11 20",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-come-centre",
    name: "Pharmacie de Comé",
    address: "Carrefour Comé, RNIE 1",
    city: "Comé",
    department: "Mono",
    latitude: 6.4082,
    longitude: 1.8854,
    phone: "+229 22 43 01 18",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-grand-popo",
    name: "Pharmacie de Grand-Popo",
    address: "Route Côtière, Grand-Popo",
    city: "Grand-Popo",
    department: "Mono",
    latitude: 6.2812,
    longitude: 1.8215,
    phone: "+229 22 43 50 12",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },

  // Aplahoué & Djakotomey (Couffo)
  {
    id: "ph-aplahoue-centrale",
    name: "Pharmacie Centrale d'Aplahoué",
    address: "Quartier Azovè, RNIE 4",
    city: "Aplahoué",
    department: "Couffo",
    latitude: 6.9345,
    longitude: 1.7654,
    phone: "+229 22 46 01 15",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-klouekanme",
    name: "Pharmacie de Klouékanmè",
    address: "Centre Commercial de Klouékanmè",
    city: "Klouékanmè",
    department: "Couffo",
    latitude: 6.9854,
    longitude: 1.8485,
    phone: "+229 22 47 02 18",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },

  // Dassa, Savalou, Savè (Collines)
  {
    id: "ph-dassa-centrale",
    name: "Pharmacie des 41 Collines",
    address: "Carrefour Dassa, RNIE 2",
    city: "Dassa-Zoumé",
    department: "Collines",
    latitude: 7.7523,
    longitude: 2.1854,
    phone: "+229 22 53 02 11",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-savalou-centrale",
    name: "Pharmacie Principale de Savalou",
    address: "Face Palais Royal de Savalou",
    city: "Savalou",
    department: "Collines",
    latitude: 7.9285,
    longitude: 1.9754,
    phone: "+229 22 54 02 15",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-save-centrale",
    name: "Pharmacie des Mamelles de Savè",
    address: "Avenue Principale de Savè",
    city: "Savè",
    department: "Collines",
    latitude: 8.0345,
    longitude: 2.4854,
    phone: "+229 22 56 01 22",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },

  // Pobè, Sakété, Kétou (Plateau)
  {
    id: "ph-pobe-centrale",
    name: "Pharmacie Centrale de Pobè",
    address: "Place du Marché de Pobè",
    city: "Pobè",
    department: "Plateau",
    latitude: 6.9812,
    longitude: 2.6654,
    phone: "+229 20 27 02 10",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-sakete-centre",
    name: "Pharmacie de Sakété",
    address: "Carrefour Sakété Centre",
    city: "Sakété",
    department: "Plateau",
    latitude: 6.7385,
    longitude: 2.6585,
    phone: "+229 20 25 01 18",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-ketou-centre",
    name: "Pharmacie Royale de Kétou",
    address: "Quartier Idéna, Kétou",
    city: "Kétou",
    department: "Plateau",
    latitude: 7.3625,
    longitude: 2.6012,
    phone: "+229 20 28 01 14",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },

  // Allada & Ouidah environs (Atlantique)
  {
    id: "ph-allada-centre",
    name: "Pharmacie Centrale d'Allada",
    address: "Carrefour Hôpital d'Allada",
    city: "Allada",
    department: "Atlantique",
    latitude: 6.6654,
    longitude: 2.1523,
    phone: "+229 21 36 02 30",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-torri-bossito",
    name: "Pharmacie de Tori-Bossito",
    address: "Carrefour Tori Centre",
    city: "Tori-Bossito",
    department: "Atlantique",
    latitude: 6.5012,
    longitude: 2.1485,
    phone: "+229 21 36 60 18",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-kpomasse",
    name: "Pharmacie de Kpomassè",
    address: "Centre-Ville Kpomassè",
    city: "Kpomassè",
    department: "Atlantique",
    latitude: 6.4012,
    longitude: 2.0512,
    phone: "+229 21 34 33 20",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-bembereke-centrale",
    name: "Pharmacie Centrale de Bembèrèkè",
    address: "Avenue Principale, Bembèrèkè",
    city: "Bembèrèkè",
    department: "Borgou",
    latitude: 10.2285,
    longitude: 2.6685,
    phone: "+229 23 68 02 11",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-tchaourou-centre",
    name: "Pharmacie de Tchaourou",
    address: "Carrefour Marché, Tchaourou",
    city: "Tchaourou",
    department: "Borgou",
    latitude: 8.8854,
    longitude: 2.5985,
    phone: "+229 23 62 02 18",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-nikki-centre",
    name: "Pharmacie Centrale de Nikki",
    address: "Face Palais de l'Empereur, Nikki",
    city: "Nikki",
    department: "Borgou",
    latitude: 9.9385,
    longitude: 3.2085,
    phone: "+229 23 68 50 14",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-ndali-centre",
    name: "Pharmacie de N'Dali",
    address: "Carrefour N'Dali, RNIE 2",
    city: "N'Dali",
    department: "Borgou",
    latitude: 9.8585,
    longitude: 2.7185,
    phone: "+229 23 61 70 12",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-kouande-centre",
    name: "Pharmacie de Kouandé",
    address: "Centre-Ville Kouandé",
    city: "Kouandé",
    department: "Atacora",
    latitude: 10.3345,
    longitude: 1.6854,
    phone: "+229 23 84 01 12",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-kerou-centre",
    name: "Pharmacie de Kérou",
    address: "Route de Banikoara, Kérou",
    city: "Kérou",
    department: "Atacora",
    latitude: 10.8412,
    longitude: 2.0654,
    phone: "+229 23 84 50 20",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-ouake-centre",
    name: "Pharmacie de Ouaké",
    address: "Carrefour Ouaké, RNIE 3",
    city: "Ouaké",
    department: "Donga",
    latitude: 9.6612,
    longitude: 1.3854,
    phone: "+229 23 80 40 10",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-copargo-centre",
    name: "Pharmacie de Copargo",
    address: "Centre Commercial de Copargo",
    city: "Copargo",
    department: "Donga",
    latitude: 9.8345,
    longitude: 1.5485,
    phone: "+229 23 80 60 14",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-bante-centre",
    name: "Pharmacie de Bantè",
    address: "Place du Marché, Bantè",
    city: "Bantè",
    department: "Collines",
    latitude: 8.4125,
    longitude: 1.8854,
    phone: "+229 22 54 50 18",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-ouesse-centre",
    name: "Pharmacie de Ouèssè",
    address: "Quartier Gare, Ouèssè",
    city: "Ouèssè",
    department: "Collines",
    latitude: 8.4854,
    longitude: 2.4215,
    phone: "+229 22 56 40 10",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-djakotomey",
    name: "Pharmacie de Djakotomey",
    address: "Grand Carrefour Djakotomey",
    city: "Djakotomey",
    department: "Couffo",
    latitude: 6.9012,
    longitude: 1.7185,
    phone: "+229 22 46 55 12",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-lalo",
    name: "Pharmacie de Lalo",
    address: "Centre-Ville Lalo",
    city: "Lalo",
    department: "Couffo",
    latitude: 6.9215,
    longitude: 1.8854,
    phone: "+229 22 47 40 15",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-athieme",
    name: "Pharmacie d'Athiémé",
    address: "Bordure Fleuve Mono, Athiémé",
    city: "Athiémé",
    department: "Mono",
    latitude: 6.5812,
    longitude: 1.6712,
    phone: "+229 22 41 50 18",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-adjohoun-centre",
    name: "Pharmacie d'Adjohoun",
    address: "Marché Azowlissè, Vallée Ouémé",
    city: "Adjohoun",
    department: "Ouémé",
    latitude: 6.7025,
    longitude: 2.4854,
    phone: "+229 20 26 02 14",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
  {
    id: "ph-dangbo-centre",
    name: "Pharmacie de Dangbo",
    address: "Carrefour Dangbo, Route de Porto-Novo",
    city: "Dangbo",
    department: "Ouémé",
    latitude: 6.5854,
    longitude: 2.5512,
    phone: "+229 20 26 50 11",
    is_on_duty: false,
    duty_start_date: "2026-09-07",
    duty_end_date: "2026-09-14",
  },
  {
    id: "ph-ifangni-centre",
    name: "Pharmacie d'Ifangni",
    address: "Carrefour Frontière Igolo, Ifangni",
    city: "Ifangni",
    department: "Plateau",
    latitude: 6.6454,
    longitude: 2.7112,
    phone: "+229 20 25 50 18",
    is_on_duty: true,
    duty_start_date: "2026-09-14",
    duty_end_date: "2026-09-21",
  },
];
